In [24]:
import numpy as np

#matrixf=open("B_ellTotal1234.txt")#open file 
#matrixfbase=matrixf.readlines()#reads file line by line
#matrix_Bell=np.array([i.split(",")[0] for i in (matrixfbase)])#extract bells
#matrix_ell1=np.array([i.split(",")[1] for i in (matrixfbase)])#extracts ell1
#matrix_ell2=np.array([i.split(",")[2] for i in (matrixfbase)])#extracts ell2
#matrix_ell3=np.array([i.split(",")[3] for i in (matrixfbase)])#extracts ell3
#matrix_ell23=np.array([abs(float(i.split(",")[2])-float(i.split(",")[3])) for i in (matrixfbase)]) #subtracts l2-l3

matrixf = np.loadtxt("B_ellTotal1234.txt", delimiter=',')
matrix_Bell = matrixf[:,0]
matrix_ell1 = matrixf[:,1]
matrix_ell23 = matrixf[:,3]-matrixf[:,2]
matrix_ell23mirror = matrixf[:,2] - matrixf[:,3]
print matrix_ell23
print matrix_ell23mirror

[ 0.  1.  2.  0.  3.  1.  4.  2.  0.  5.  3.  1.  6.  4.  2.  0.  7.  5.
  3.  1.  8.  6.  4.  2.  0.  9.  7.  5.  3.  1. 10.  8.  6.  4.  2.  0.
 11.  9.  7.  5.  3.  1. 12. 10.  8.  6.  4.  2.  0. 13. 11.  9.  7.  5.
  3.  1. 14. 12. 10.  8.  6.  4.  2.  0. 15. 13. 11.  9.  7.  5.  3.  1.
 12. 10.  8.  6.  4.  2.  0.  9.  7.  5.  3.  1.  6.  4.  2.  0.  3.  1.
  0.]
[  0.  -1.  -2.   0.  -3.  -1.  -4.  -2.   0.  -5.  -3.  -1.  -6.  -4.
  -2.   0.  -7.  -5.  -3.  -1.  -8.  -6.  -4.  -2.   0.  -9.  -7.  -5.
  -3.  -1. -10.  -8.  -6.  -4.  -2.   0. -11.  -9.  -7.  -5.  -3.  -1.
 -12. -10.  -8.  -6.  -4.  -2.   0. -13. -11.  -9.  -7.  -5.  -3.  -1.
 -14. -12. -10.  -8.  -6.  -4.  -2.   0. -15. -13. -11.  -9.  -7.  -5.
  -3.  -1. -12. -10.  -8.  -6.  -4.  -2.   0.  -9.  -7.  -5.  -3.  -1.
  -6.  -4.  -2.   0.  -3.  -1.   0.]


In [25]:
Y = matrix_ell1#matrix_ell1#set the x dimension form matrix shape 
#print Y 
#print max(Y), min(Y)
a = Y.max()
b = np.min(Y)
#print a,b
Yarr = np.arange(int(b),int(a)+1)
print Yarr
print Y

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0.  1.  2.  2.  3.  3.  4.  4.  4.  5.  5.  5.  6.  6.  6.  6.  7.  7.
  7.  7.  8.  8.  8.  8.  8.  9.  9.  9.  9.  9. 10. 10. 10. 10. 10. 10.
 11. 11. 11. 11. 11. 11. 12. 12. 12. 12. 12. 12. 12. 13. 13. 13. 13. 13.
 13. 13. 14. 14. 14. 14. 14. 14. 14. 14. 15. 15. 15. 15. 15. 15. 15. 15.
 16. 16. 16. 16. 16. 16. 16. 17. 17. 17. 17. 17. 18. 18. 18. 18. 19. 19.
 20.]


In [26]:
X = matrix_ell23#matrix_ell1#set the x dimension form matrix shape 
#Xa = matrix_ell23mirror
#print Y 
print max(X), min(X)
a = X.max()
b = np.min(X)
#print a,b
Xarr = np.arange(int(b), int(a)+1)
print Xarr
print X

15.0 0.0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0.  1.  2.  0.  3.  1.  4.  2.  0.  5.  3.  1.  6.  4.  2.  0.  7.  5.
  3.  1.  8.  6.  4.  2.  0.  9.  7.  5.  3.  1. 10.  8.  6.  4.  2.  0.
 11.  9.  7.  5.  3.  1. 12. 10.  8.  6.  4.  2.  0. 13. 11.  9.  7.  5.
  3.  1. 14. 12. 10.  8.  6.  4.  2.  0. 15. 13. 11.  9.  7.  5.  3.  1.
 12. 10.  8.  6.  4.  2.  0.  9.  7.  5.  3.  1.  6.  4.  2.  0.  3.  1.
  0.]


In [27]:
sizex = Xarr.size
print sizex
print Yarr.size
Bellmatrix = np.zeros((Xarr.size,Yarr.size))
print Bellmatrix

16
21
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0.

In [28]:
for i in np.arange(matrix_Bell.size):    
    #print int(matrix_ell23[i]),int(matrix_ell1[i])
    Bellmatrix[int(matrix_ell23t[i]),int(matrix_ell1t[i])]=matrix_Bellt[i]
    #Bellmatrix[]
#print Bellmatrix

NameError: name 'matrix_Bellt' is not defined

In [ ]:
import matplotlib.pyplot as plt
cp = plt.contourf(Yarr, Xarr, Bellmatrix.T)
print Yarr.size, Bellmatrix[0,:].size
#plt.colormap()
plt.colorbar(cp)
plt.show()